# Lib services required in development and production env
# Services that cannot be updated by end user
version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - huebot-net

  nginx:
    image: ghcr.io/huebot-iot/nginx:1.0.3
    restart: unless-stopped
    network_mode: "host"

  mqtt_broker:
    image: ghcr.io/huebot-iot/mqtt:1.2.1
    restart: unless-stopped
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/config.json:/etc/mosquitto/huebot.config
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - 18831:1883
    networks:
      - huebot-net

  api:
    image: ghcr.io/huebot-iot/hub-core-api:0.1.7
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/local/bin/huebot/db:/usr/db
      - /usr/local/bin/huebot/config.json:/usr/app/huebot-config.json
      - /usr/local/bin/mosquitto/config.json:/usr/app/mqtt-config.json
    ports:
      - 3000:3000
    networks:
      - huebot-net

  native:
    image: ghcr.io/huebot-iot/hub-core-native:0.1.2
    privileged: true
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/NetworkManager:/etc/NetworkManager
      - /var/run/dbus:/var/run/dbus
    ports:
      - 9000:9000
    networks:
      - huebot-net

  mqtt:
    image: ghcr.io/huebot-iot/hub-core-mqtt:0.1.2
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - /usr/local/bin/mosquitto/config.json:/usr/app/mqtt-config.json
    networks:
      - huebot-net

  ble:
    image: ghcr.io/huebot-iot/hub-ble:0.1.2
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - /usr/local/bin/huebot/config.json:/usr/src/huebot-config.json

networks:
  huebot-net:
    name: hubNetwork
    driver: bridge
